### PR TITLE
Applied some best practice for both shellscripts

### PR DESCRIPTION
**Pull request by schorsch3000**
I had a problem with a gif with a space in it's name and found the culprit in `run_in_venv.sh`
While fixing that i applied shell best practice to both shell-scripts.

btw: thanks for the work done, i'm in love :-)

### CODE REVIEW

**Comment by schorsch3000** [comment]
i'm sorry,
71bc5ff should have been another pullrequest to be able to set your bluetooth address as an env-var.
If it's okay to you i'l keep it combined, if not i'm happty to extract and make a seperatly PR out of it.

**Comment by derkalle4** [comment]
Hi Schorsch,

many thanks for your pull request! Normally you should do two pull requests instead of one. But because this is a tiny change I am happily accept it. Thanks for your help, even if I am far from finishing this project :)

Kind Regards,
Kalle

**Comment by derkalle4** [comment]
If you like I would add you to our list of contributors.

**Comment by schorsch3000** [comment]
> Normally you should do two pull requests instead of one.
I absolutely should have and i intended to.
this was just an accident :-)

> If you like I would add you to our list of contributors.

I'm not asking for it, especially not for such a tiny change, but i'm not denying it either, so go for it if you like :-)


> Thanks for your help, even if I am far from finishing this project
I's quite usable right now, just text-display is missing to have it complete usable for my use case right now

**Comment by derkalle4** [comment]
Hi schorsch,

the ability to display text is on my road map. Will be added soon. I am currently busy because of the Chaos Communication Congress where I move around with such an iDotMatrix Display on my backpack (because I can :D).

**Pull request merged**
