### PR TITLE
GUI + Device Finder

### PR DESCRIPTION
**Pull request by TheBigWazz**
Built GUI with Device Finder.

Provided Build scripts for Windows and Linux.

Added basic program icon.

Updated README with GUI information.

### CODE REVIEW

**Comment by TheBigWazz** [comment]
Hi there derkalle4!

I've been a big fan of this project as of recently! I tried my hand as soldering into the hardware a few weeks ago, but failed miserably, thus, a GUI is born instead. 

Much thanks to you and the other contributors for making such a great project to build off of! Hope your health is improving and that you're finding time to do the things you enjoy. 

-tbw

**Comment by derkalle4** [comment]
@TheBigWazz many thanks for your help! Would have been much more progress if life would be easier on me. Anyway, I am happily merge your pull request to have this project going forward. Whenever I have enough energy to further work on this I'll update it. But feel free to discuss changes at any given time:)

**Comment by TheBigWazz** [comment]
@derkalle4 After reviewing my additions, I realized the file structure should be slightly adjusted to have the GUI files under the main folder. If the user uses the build script, the program should be moved to the main folder as well.

**Comment by derkalle4** [comment]
@TheBigWazz feel free to push another pull-request if still necessary :)

**Pull request merged**
