### PR TITLE
Added OpenAI-based assistant

### PR DESCRIPTION
**Pull request by reallyrehan**
Hi @derkalle4 , I recently bought a Idotmatrix screen and while playing around, found your repo - amazing work!

Thought it would be cool to be able to control my screen using natural language. Have added a command-line based interactive assistant that uses gpt-4o-mini to convert natural language into function calls.

It supports all of the functionality that is currently supported in the [client](https://github.com/derkalle4/python3-idotmatrix-client/tree/main). The setup is super simple, also added a guide. All you need is an OpenAI key - hoping to also add support for multiple agents soon as well as a web-app based chat UI.

### CODE REVIEW

**Comment by derkalle4** [comment]
Hi @reallyrehan 

Many thanks for your pull request! Sounds great to have natural language processing integrated. However, I would like to discuss whether it should be included in the client or if one should use the library from my other repository to create a separated app. Same would go for an home assistant integration which should be another repository consuming the library.

Also: if we implement it into the client we should care about integrating every command line stuff into the GUI which is now partly implemented thanks to another pull-request :)

Unfortunately I haven't found the energy to further look into the commits to streamline them.

However: I would like to get some opinions from other users of this client / the library.

Kind Regards,
Kalle

**Comment by schorsch3000** [comment]
I don't think this should be a core feature, this easily could be a separate project using the lib, with no problems at all.

**Comment by reallyrehan** [comment]
Hi @derkalle4 @schorsch3000 , thanks for your feedback!

On second thought, I agree with your views - would make more sense to make it a separate repo. I'll try to do that once I get some time - would appreciate if you have any feedback on implementation as well.

Closing this PR for now!

**Comment by derkalle4** [comment]
@reallyrehan I could give a starting point with a repository as well. But will take some weeks unfortunately. Will not have enough time to have a third repository I cannot really work on.

**Pull request closed without merging**
